---
name: "[lemonde.fr] scrap and cook obituaries"

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
  repository_dispatch:
    types:
      - new_article

jobs:
  scrap_commit:
    name: "scrap and commit new data"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "install dependencies"
        run: |
          pip install -r requirements.txt
      - name: "scrap rss feed"
        run: |
          python scrap_rss.py
      - name: "cook list of articles"
        run: |
          python cook_articles.py
      - name: "cook list of new articles"
        run: |
          python cook_articles_new.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🤖📰 récupère les articles du jour"
          file_pattern: "**/*.csv *.csv"

